# Generated by Django 3.2.4 on 2021-11-13 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_blog', '0003_auto_20211111_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title_tag',
            new_name='description',
        ),
    ]
