# Generated by Django 4.1.2 on 2022-10-15 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_blog', '0004_rename_title_tag_post_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
