# Generated by Django 3.2.4 on 2021-07-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_blog', '0005_auto_20210703_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='No category', max_length=50),
        ),
    ]
