# Generated by Django 4.1.2 on 2022-11-07 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_blog', '0005_remove_post_category_delete_postcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(default='miscellaneous', max_length=70, unique=True)),
            ],
            options={
                'verbose_name': 'category_name',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
