# Generated by Django 4.1.2 on 2022-11-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_blog', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=70, null=True),
        ),
    ]
