# Generated by Django 4.1.2 on 2022-11-24 22:20

from django.db import migrations, models
import prose.fields


class Migration(migrations.Migration):

    dependencies = [
        ('the_blog', '0010_alter_post_options_remove_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=prose.fields.RichTextField(),
        ),
    ]
