# Generated by Django 4.1.2 on 2022-11-25 00:51

from django.db import migrations, models
import prose.fields


class Migration(migrations.Migration):

    dependencies = [
        ('the_blog', '0011_alter_category_slug_alter_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', prose.fields.DocumentContentField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
