# Generated by Django 4.1.2 on 2022-11-24 22:12

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=150, validators=[account.models.validate_field_has_no_whitesapce]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=150, validators=[account.models.validate_field_has_no_whitesapce]),
        ),
    ]
