# Generated by Django 3.2.4 on 2021-07-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Binary', 'Binary'), ('Non-Binary', 'Non-Binary'), ('Genderfluid', 'Genderfluid'), ('Agender', 'Agender'), ('Bigender', 'Bigender'), ('Polygender', 'Polygender'), ('Neutrois', 'Neutrois'), ('Gender Apathetic', 'Gender Apathetic'), ('Intergender', 'Intergender')], default='Male', max_length=19),
        ),
    ]
